"""
Analyzes one's VK audios.
Input: csv.
Output: ???
"""

import os
import pandas as pd
import numpy as np

# input_filename = 'output.csv'
list_of_csvs = [] # get the names of all csvs in the current dir
# print them all, example: #1 - one.csv; #2 - two.csv; #3 - asdasd.csv

# # ask the user what number they like the most
# filenumber = input('# of the required .csv-file:')

# filename = list_of_csvs[filenumber]
filename = "output_20160630_021254.csv"
df = pd.read_csv(filename, header=None, names=['artist', 'track', \
                                               'length', 'link'])

df.artist = [a.lower().strip() for a in df.artist]


def make_artists_table(df = df):

    # Takes a dataframe generated by vk_playlist.py
    # Makes a leaderboard of artists sorted (desc)
    # by number of tracks performed by this artist

    # Example:
    #In [164]: artists.head()
    #Out[164]: 
    #                artist count
    #54              ayreon    29
    #400         pink floyd    22
    #514  the dust brothers    14
    #363               muse    14
    #415      ramin djawadi    14
    table = pd.pivot_table(df, index=['artist'], values = 'track', aggfunc=len)
    artists = pd.DataFrame([np.array(table.axes[0]), np.array(table)]
                            ).transpose().rename_axis(
                                    {0: "artist", 1: "count"}, axis = 'columns'
                            ).sort_values(by = 'count', ascending = False)
    return artists


def analyze_artists(df = df):

    print("*** *** ***")
    artists = make_artists_table(df = df)
    n = len(artists)
    print("We have found {} artists in your vk playlist".format(n))
    ans = input("Wanna see them all? [Y/n]")

    if ans.lower().strip() == 'y':
        for i in range(len(artists)):
            print("{} – {} tracks".format(artists.iloc[i][0], 
                                        artists.iloc[i][1]))


if __name__ == '__main__':
    analyze_artists()